export const EMOJI_CATEGORIES = [
    { id: 'smileys', label: 'Smileys', icon: '😊' },
    { id: 'people', label: 'People', icon: '👋' },
    { id: 'animals', label: 'Animals', icon: '🐶' },
    { id: 'food', label: 'Food', icon: '🍎' },
    { id: 'activities', label: 'Activities', icon: '⚽' },
    { id: 'travel', label: 'Travel', icon: '🚗' },
    { id: 'objects', label: 'Objects', icon: '💡' },
    { id: 'symbols', label: 'Symbols', icon: '❤️' },
    { id: 'flags', label: 'Flags', icon: '🏁' }
];

export const ALL_EMOJIS = [
    // Smileys & Emotion
    { char: '😀', category: 'smileys', keywords: 'grinning face happy' },
    { char: '😃', category: 'smileys', keywords: 'smiley happy joy' },
    { char: '😄', category: 'smileys', keywords: 'smile happy joy' },
    { char: '😁', category: 'smileys', keywords: 'grin happy' },
    { char: '😆', category: 'smileys', keywords: 'laugh haha lol' },
    { char: '😅', category: 'smileys', keywords: 'sweat smile happy' },
    { char: '🤣', category: 'smileys', keywords: 'rofl laugh' },
    { char: '😂', category: 'smileys', keywords: 'joy haha lol' },
    { char: '🙂', category: 'smileys', keywords: 'slight smile' },
    { char: '🙃', category: 'smileys', keywords: 'upside down' },
    { char: '😉', category: 'smileys', keywords: 'wink' },
    { char: '😊', category: 'smileys', keywords: 'blush happy' },
    { char: '😇', category: 'smileys', keywords: 'angel innocent' },
    { char: '🥰', category: 'smileys', keywords: 'love hearts' },
    { char: '😍', category: 'smileys', keywords: 'heart eyes love' },
    { char: '🤩', category: 'smileys', keywords: 'star eyes wow' },
    { char: '😘', category: 'smileys', keywords: 'kiss love' },
    { char: '😗', category: 'smileys', keywords: 'kiss' },
    { char: '☺️', category: 'smileys', keywords: 'relaxed happy' },
    { char: '😋', category: 'smileys', keywords: 'yum delicious' },
    { char: '😛', category: 'smileys', keywords: 'tongue' },
    { char: '😜', category: 'smileys', keywords: 'wink tongue' },
    { char: '🤪', category: 'smileys', keywords: 'zany crazy' },
    { char: '😝', category: 'smileys', keywords: 'squint tongue' },
    { char: '🤑', category: 'smileys', keywords: 'money mouth' },
    { char: '🤗', category: 'smileys', keywords: 'hugs' },
    { char: '🤭', category: 'smileys', keywords: 'hand over mouth' },
    { char: '🤫', category: 'smileys', keywords: 'shush quiet' },
    { char: '🤔', category: 'smileys', keywords: 'thinking hmm' },
    { char: '🤐', category: 'smileys', keywords: 'zipper mouth' },
    { char: '🤨', category: 'smileys', keywords: 'raised eyebrow' },
    { char: '😐', category: 'smileys', keywords: 'neutral' },
    { char: '😑', category: 'smileys', keywords: 'expressionless' },
    { char: '😶', category: 'smileys', keywords: 'no mouth' },
    { char: '😏', category: 'smileys', keywords: 'smirk' },
    { char: '😒', category: 'smileys', keywords: 'unamused' },
    { char: '🙄', category: 'smileys', keywords: 'eye roll' },
    { char: '😬', category: 'smileys', keywords: 'grimace' },
    { char: '🤥', category: 'smileys', keywords: 'lying' },
    { char: '😌', category: 'smileys', keywords: 'relieved' },
    { char: '😔', category: 'smileys', keywords: 'pensive' },
    { char: '😪', category: 'smileys', keywords: 'sleepy' },
    { char: '🤤', category: 'smileys', keywords: 'drool' },
    { char: '😴', category: 'smileys', keywords: 'sleeping' },
    { char: '😷', category: 'smileys', keywords: 'mask' },
    { char: '🤒', category: 'smileys', keywords: 'fever' },
    { char: '🤕', category: 'smileys', keywords: 'bandage' },
    { char: '🤢', category: 'smileys', keywords: 'nauseated' },
    { char: '🤮', category: 'smileys', keywords: 'vomit' },
    { char: '🤧', category: 'smileys', keywords: 'sneeze' },
    { char: '🥵', category: 'smileys', keywords: 'hot' },
    { char: '🥶', category: 'smileys', keywords: 'cold' },
    { char: '🥴', category: 'smileys', keywords: 'woozy' },
    { char: '😵', category: 'smileys', keywords: 'dizzy' },
    { char: '🤯', category: 'smileys', keywords: 'exploding head' },
    { char: '🤠', category: 'smileys', keywords: 'cowboy' },
    { char: '🥳', category: 'smileys', keywords: 'party' },
    { char: '😎', category: 'smileys', keywords: 'cool sunglasses' },
    { char: '🤓', category: 'smileys', keywords: 'nerd' },
    { char: '🧐', category: 'smileys', keywords: 'monocle' },
    { char: '😕', category: 'smileys', keywords: 'confused' },
    { char: '😟', category: 'smileys', keywords: 'worried' },
    { char: '🙁', category: 'smileys', keywords: 'slight frown' },
    { char: '😮', category: 'smileys', keywords: 'open mouth wow' },
    { char: '😯', category: 'smileys', keywords: 'hushed' },
    { char: '😲', category: 'smileys', keywords: 'astonished' },
    { char: '😳', category: 'smileys', keywords: 'flushed' },
    { char: '🥺', category: 'smileys', keywords: 'pleading' },
    { char: '😦', category: 'smileys', keywords: 'frown open mouth' },
    { char: '😧', category: 'smileys', keywords: 'anguished' },
    { char: '😨', category: 'smileys', keywords: 'fearful' },
    { char: '😰', category: 'smileys', keywords: 'blue sweat' },
    { char: '😥', category: 'smileys', keywords: 'sad sweat' },
    { char: '😢', category: 'smileys', keywords: 'cry' },
    { char: '😭', category: 'smileys', keywords: 'sob' },
    { char: '😱', category: 'smileys', keywords: 'scream fear' },
    { char: '😖', category: 'smileys', keywords: 'confounded' },
    { char: '😣', category: 'smileys', keywords: 'persevere' },
    { char: '😞', category: 'smileys', keywords: 'disappointed' },
    { char: '😓', category: 'smileys', keywords: 'sweat' },
    { char: '😩', category: 'smileys', keywords: 'weary' },
    { char: '😫', category: 'smileys', keywords: 'tired' },
    { char: '🥱', category: 'smileys', keywords: 'yawn' },
    { char: '😤', category: 'smileys', keywords: 'triumph' },
    { char: '😡', category: 'smileys', keywords: 'pouty angry' },
    { char: '😠', category: 'smileys', keywords: 'angry' },
    { char: '🤬', category: 'smileys', keywords: 'cursing' },
    { char: '😈', category: 'smileys', keywords: 'smile devil' },
    { char: '👿', category: 'smileys', keywords: 'angry devil' },
    { char: '💀', category: 'smileys', keywords: 'skull' },
    { char: '💩', category: 'smileys', keywords: 'poop' },
    { char: '🤡', category: 'smileys', keywords: 'clown' },
    { char: '👻', category: 'smileys', keywords: 'ghost' },
    { char: '👽', category: 'smileys', keywords: 'alien' },
    { char: '👾', category: 'smileys', keywords: 'alien monster' },
    { char: '🤖', category: 'smileys', keywords: 'robot' },

    // People & Body
    { char: '👋', category: 'people', keywords: 'wave hello hi' },
    { char: '🤚', category: 'people', keywords: 'raised back of hand' },
    { char: '🖐️', category: 'people', keywords: 'raised hand fingers splayed' },
    { char: '✋', category: 'people', keywords: 'raised hand halt stop' },
    { char: '🖖', category: 'people', keywords: 'vulcan salute' },
    { char: '👌', category: 'people', keywords: 'ok hand' },
    { char: '🤏', category: 'people', keywords: 'pinching hand' },
    { char: '✌️', category: 'people', keywords: 'victory peace' },
    { char: '🤞', category: 'people', keywords: 'fingers crossed' },
    { char: '🤟', category: 'people', keywords: 'love you' },
    { char: '🤘', category: 'people', keywords: 'rock on' },
    { char: '🤙', category: 'people', keywords: 'call me' },
    { char: '👈', category: 'people', keywords: 'point left' },
    { char: '👉', category: 'people', keywords: 'point right' },
    { char: '👆', category: 'people', keywords: 'point up' },
    { char: '👇', category: 'people', keywords: 'point down' },
    { char: '☝️', category: 'people', keywords: 'point up' },
    { char: '👍', category: 'people', keywords: 'thumbs up' },
    { char: '👎', category: 'people', keywords: 'thumbs down' },
    { char: '✊', category: 'people', keywords: 'fist' },
    { char: '👊', category: 'people', keywords: 'oncoming fist' },
    { char: '🤛', category: 'people', keywords: 'left fist' },
    { char: '🤜', category: 'people', keywords: 'right fist' },
    { char: '👏', category: 'people', keywords: 'clap' },
    { char: '🙌', category: 'people', keywords: 'hands up' },
    { char: '👐', category: 'people', keywords: 'open hands' },
    { char: '🤲', category: 'people', keywords: 'palms up' },
    { char: '🤝', category: 'people', keywords: 'handshake' },
    { char: '🙏', category: 'people', keywords: 'pray' },
    { char: '✍️', category: 'people', keywords: 'write' },
    { char: '💅', category: 'people', keywords: 'nails' },
    { char: '🤳', category: 'people', keywords: 'selfie' },
    { char: '💪', category: 'people', keywords: 'strong muscle' },
    { char: '🦵', category: 'people', keywords: 'leg' },
    { char: '🦶', category: 'people', keywords: 'foot' },
    { char: '👂', category: 'people', keywords: 'ear' },
    { char: '🦻', category: 'people', keywords: 'hearing aid' },
    { char: '👃', category: 'people', keywords: 'nose' },
    { char: '🧠', category: 'people', keywords: 'brain' },
    { char: '🦷', category: 'people', keywords: 'tooth' },
    { char: '🦴', category: 'people', keywords: 'bone' },
    { char: '👀', category: 'people', keywords: 'eyes' },
    { char: '👁️', category: 'people', keywords: 'eye' },
    { char: '👅', category: 'people', keywords: 'tongue' },
    { char: '👄', category: 'people', keywords: 'mouth' },
    { char: '👶', category: 'people', keywords: 'baby' },
    { char: '🧒', category: 'people', keywords: 'child' },
    { char: '👦', category: 'people', keywords: 'boy' },
    { char: '👧', category: 'people', keywords: 'girl' },
    { char: '🧑', category: 'people', keywords: 'person' },
    { char: '👨', category: 'people', keywords: 'man' },
    { char: '👩', category: 'people', keywords: 'woman' },
    { char: '🧓', category: 'people', keywords: 'older person' },
    { char: '👴', category: 'people', keywords: 'old man' },
    { char: '👵', category: 'people', keywords: 'old woman' },

    // Animals & Nature
    { char: '🐶', category: 'animals', keywords: 'dog' },
    { char: '🐱', category: 'animals', keywords: 'cat' },
    { char: '🐭', category: 'animals', keywords: 'mouse' },
    { char: '🐹', category: 'animals', keywords: 'hamster' },
    { char: '🐰', category: 'animals', keywords: 'rabbit' },
    { char: '🦊', category: 'animals', keywords: 'fox' },
    { char: '🐻', category: 'animals', keywords: 'bear' },
    { char: '🐼', category: 'animals', keywords: 'panda' },
    { char: '🐨', category: 'animals', keywords: 'koala' },
    { char: '🐯', category: 'animals', keywords: 'tiger' },
    { char: '🦁', category: 'animals', keywords: 'lion' },
    { char: '🐮', category: 'animals', keywords: 'cow' },
    { char: '🐷', category: 'animals', keywords: 'pig' },
    { char: '🐽', category: 'animals', keywords: 'pig nose' },
    { char: '🐸', category: 'animals', keywords: 'frog' },
    { char: '🐵', category: 'animals', keywords: 'monkey' },
    { char: '🙊', category: 'animals', keywords: 'no speak monkey' },
    { char: '🐒', category: 'animals', keywords: 'monkey' },
    { char: '🐔', category: 'animals', keywords: 'chicken' },
    { char: '🐧', category: 'animals', keywords: 'penguin' },
    { char: '🐦', category: 'animals', keywords: 'bird' },
    { char: '🐤', category: 'animals', keywords: 'baby chick' },
    { char: '🦆', category: 'animals', keywords: 'duck' },
    { char: '🦅', category: 'animals', keywords: 'eagle' },
    { char: '🦉', category: 'animals', keywords: 'owl' },
    { char: '🦇', category: 'animals', keywords: 'bat' },
    { char: '🐺', category: 'animals', keywords: 'wolf' },
    { char: '🐗', category: 'animals', keywords: 'boar' },
    { char: '🐴', category: 'animals', keywords: 'horse' },
    { char: '🦄', category: 'animals', keywords: 'unicorn' },
    { char: '🐝', category: 'animals', keywords: 'bee' },
    { char: '🐛', category: 'animals', keywords: 'bug' },
    { char: '🦋', category: 'animals', keywords: 'butterfly' },
    { char: '🐌', category: 'animals', keywords: 'snail' },
    { char: '🐞', category: 'animals', keywords: 'ladybug' },
    { char: '🐜', category: 'animals', keywords: 'ant' },
    { char: '🦟', category: 'animals', keywords: 'mosquito' },
    { char: '🐢', category: 'animals', keywords: 'turtle' },
    { char: '🐍', category: 'animals', keywords: 'snake' },
    { char: '🦎', category: 'animals', keywords: 'lizard' },
    { char: '🦖', category: 'animals', keywords: 't-rex' },
    { char: '🐙', category: 'animals', keywords: 'octopus' },
    { char: '🦑', category: 'animals', keywords: 'squid' },
    { char: '🦐', category: 'animals', keywords: 'shrimp' },
    { char: '🦀', category: 'animals', keywords: 'crab' },
    { char: '🐡', category: 'animals', keywords: 'blowfish' },
    { char: '🐠', category: 'animals', keywords: 'tropical fish' },
    { char: '🐟', category: 'animals', keywords: 'fish' },
    { char: '🐬', category: 'animals', keywords: 'dolphin' },
    { char: '🐳', category: 'animals', keywords: 'whale' },
    { char: '🐋', category: 'animals', keywords: 'whale' },
    { char: '🦈', category: 'animals', keywords: 'shark' },
    { char: '🐊', category: 'animals', keywords: 'crocodile' },
    { char: '🐅', category: 'animals', keywords: 'tiger' },
    { char: '🐆', category: 'animals', keywords: 'leopard' },
    { char: '🦓', category: 'animals', keywords: 'zebra' },
    { char: '🦍', category: 'animals', keywords: 'gorilla' },
    { char: '🐘', category: 'animals', keywords: 'elephant' },
    { char: '🦏', category: 'animals', keywords: 'rhino' },
    { char: '🐪', category: 'animals', keywords: 'camel' },
    { char: '🦒', category: 'animals', keywords: 'giraffe' },
    { char: '🐃', category: 'animals', keywords: 'water buffalo' },
    { char: '🐂', category: 'animals', keywords: 'ox' },
    { char: '🐄', category: 'animals', keywords: 'cow' },
    { char: '🐎', category: 'animals', keywords: 'horse' },
    { char: '🐖', category: 'animals', keywords: 'pig' },
    { char: '🐏', category: 'animals', keywords: 'ram' },
    { char: '🐑', category: 'animals', keywords: 'sheep' },
    { char: '🐐', category: 'animals', keywords: 'goat' },
    { char: '🦌', category: 'animals', keywords: 'deer' },
    { char: '🐕', category: 'animals', keywords: 'dog' },
    { char: '🐩', category: 'animals', keywords: 'poodle' },
    { char: '🐈', category: 'animals', keywords: 'cat' },
    { char: '🐓', category: 'animals', keywords: 'rooster' },
    { char: '🦃', category: 'animals', keywords: 'turkey' },
    { char: '🕊️', category: 'animals', keywords: 'dove' },
    { char: '🐇', category: 'animals', keywords: 'rabbit' },
    { char: '🐁', category: 'animals', keywords: 'mouse' },
    { char: '🐀', category: 'animals', keywords: 'rat' },
    { char: '🐿️', category: 'animals', keywords: 'chipmunk' },
    { char: '🐾', category: 'animals', keywords: 'paw prints' },
    { char: '🐉', category: 'animals', keywords: 'dragon' },
    { char: '🌵', category: 'animals', keywords: 'cactus' },
    { char: '🎄', category: 'animals', keywords: 'christmas tree' },
    { char: '🌲', category: 'animals', keywords: 'evergreen' },
    { char: '🌳', category: 'animals', keywords: 'deciduous tree' },
    { char: '🌴', category: 'animals', keywords: 'palm tree' },
    { char: '🌱', category: 'animals', keywords: 'seedling' },
    { char: '🌿', category: 'animals', keywords: 'herb' },
    { char: '☘️', category: 'animals', keywords: 'shamrock' },
    { char: '🍀', category: 'animals', keywords: 'four leaf clover' },
    { char: '🍂', category: 'animals', keywords: 'fallen leaf' },
    { char: '🍃', category: 'animals', keywords: 'leaf' },
    { char: '🍄', category: 'animals', keywords: 'mushroom' },
    { char: '🐚', category: 'animals', keywords: 'shell' },
    { char: '🎋', category: 'animals', keywords: 'tanabata' },
    { char: '🎍', category: 'animals', keywords: 'pine decoration' },
    { char: '🌑', category: 'animals', keywords: 'new moon' },
    { char: '🌕', category: 'animals', keywords: 'full moon' },
    { char: '☀️', category: 'animals', keywords: 'sun' },
    { char: '⭐', category: 'animals', keywords: 'star' },
    { char: '🌟', category: 'animals', keywords: 'sparkle star' },
    { char: '☁️', category: 'animals', keywords: 'cloud' },
    { char: '⛅', category: 'animals', keywords: 'cloud sun' },
    { char: '⛈️', category: 'animals', keywords: 'cloud lightning rain' },
    { char: '🌧️', category: 'animals', keywords: 'cloud rain' },
    { char: '❄️', category: 'animals', keywords: 'snowflake' },
    { char: '🔥', category: 'animals', keywords: 'fire' },
    { char: '💧', category: 'animals', keywords: 'drop' },
    { char: '🌊', category: 'animals', keywords: 'wave' },

    // Food & Drink
    { char: '🍏', category: 'food', keywords: 'green apple' },
    { char: '🍎', category: 'food', keywords: 'red apple' },
    { char: '🍐', category: 'food', keywords: 'pear' },
    { char: '🍊', category: 'food', keywords: 'tangerine orange' },
    { char: '🍋', category: 'food', keywords: 'lemon' },
    { char: '🍌', category: 'food', keywords: 'banana' },
    { char: '🍉', category: 'food', keywords: 'watermelon' },
    { char: '🍇', category: 'food', keywords: 'grapes' },
    { char: '🍓', category: 'food', keywords: 'strawberry' },
    { char: '🫐', category: 'food', keywords: 'blueberries' },
    { char: '🍈', category: 'food', keywords: 'melon' },
    { char: '🍒', category: 'food', keywords: 'cherries' },
    { char: '🍑', category: 'food', keywords: 'peach' },
    { char: '🥭', category: 'food', keywords: 'mango' },
    { char: '🍍', category: 'food', keywords: 'pineapple' },
    { char: '🥥', category: 'food', keywords: 'coconut' },
    { char: '🥝', category: 'food', keywords: 'kiwi fruit' },
    { char: '🍅', category: 'food', keywords: 'tomato' },
    { char: '🍆', category: 'food', keywords: 'eggplant' },
    { char: '🥑', category: 'food', keywords: 'avocado' },
    { char: '🥦', category: 'food', keywords: 'broccoli' },
    { char: '🥬', category: 'food', keywords: 'leafy green' },
    { char: '🥒', category: 'food', keywords: 'cucumber' },
    { char: '🌽', category: 'food', keywords: 'corn' },
    { char: '🥕', category: 'food', keywords: 'carrot' },
    { char: '🫑', category: 'food', keywords: 'bell pepper' },
    { char: '🥔', category: 'food', keywords: 'potato' },
    { char: '🥐', category: 'food', keywords: 'croissant' },
    { char: '🥖', category: 'food', keywords: 'baguette' },
    { char: '🥨', category: 'food', keywords: 'pretzel' },
    { char: '🧀', category: 'food', keywords: 'cheese' },
    { char: '🥚', category: 'food', keywords: 'egg' },
    { char: '🍳', category: 'food', keywords: 'cooking egg' },
    { char: '🧈', category: 'food', keywords: 'butter' },
    { char: '🥓', category: 'food', keywords: 'bacon' },
    { char: '🥩', category: 'food', keywords: 'steak' },
    { char: '🍗', category: 'food', keywords: 'poultry leg' },
    { char: '🍖', category: 'food', keywords: 'meat on bone' },
    { char: '🌭', category: 'food', keywords: 'hot dog' },
    { char: '🍔', category: 'food', keywords: 'hamburger' },
    { char: '🍟', category: 'food', keywords: 'french fries' },
    { char: '🍕', category: 'food', keywords: 'pizza' },
    { char: '🥪', category: 'food', keywords: 'sandwich' },
    { char: '🌮', category: 'food', keywords: 'taco' },
    { char: '🌯', category: 'food', keywords: 'burrito' },
    { char: '🥗', category: 'food', keywords: 'green salad' },
    { char: '🍿', category: 'food', keywords: 'popcorn' },
    { char: '🥫', category: 'food', keywords: 'canned food' },
    { char: '🍜', category: 'food', keywords: 'steaming bowl' },
    { char: '🍝', category: 'food', keywords: 'spaghetti' },
    { char: '🍣', category: 'food', keywords: 'sushi' },
    { char: '🍤', category: 'food', keywords: 'fried shrimp' },
    { char: '🍦', category: 'food', keywords: 'soft serve' },
    { char: '🍧', category: 'food', keywords: 'shaved ice' },
    { char: '🍨', category: 'food', keywords: 'ice cream' },
    { char: '🍩', category: 'food', keywords: 'doughnut' },
    { char: '🍪', category: 'food', keywords: 'cookie' },
    { char: '🎂', category: 'food', keywords: 'birthday cake' },
    { char: '🍰', category: 'food', keywords: 'shortcake' },
    { char: '🧁', category: 'food', keywords: 'cupcake' },
    { char: '🥧', category: 'food', keywords: 'pie' },
    { char: '🍫', category: 'food', keywords: 'chocolate bar' },
    { char: '🍬', category: 'food', keywords: 'candy' },
    { char: '🍭', category: 'food', keywords: 'lollipop' },
    { char: '🍮', category: 'food', keywords: 'custard' },
    { char: '🍯', category: 'food', keywords: 'honey pot' },
    { char: '🥛', category: 'food', keywords: 'glass of milk' },
    { char: '☕', category: 'food', keywords: 'hot beverage coffee' },
    { char: '🫖', category: 'food', keywords: 'teapot' },
    { char: '🍵', category: 'food', keywords: 'teacup without handle' },
    { char: '🍶', category: 'food', keywords: 'sake' },
    { char: '🍾', category: 'food', keywords: 'bottle with popping cork' },
    { char: '🍷', category: 'food', keywords: 'wine glass' },
    { char: '🍸', category: 'food', keywords: 'cocktail glass' },
    { char: '🍹', category: 'food', keywords: 'tropical drink' },
    { char: '🍺', category: 'food', keywords: 'beer mug' },
    { char: '🍻', category: 'food', keywords: 'clinking beer mugs' },
    { char: '🥂', category: 'food', keywords: 'clinking glasses' },
    { char: '🥃', category: 'food', keywords: 'tumbler glass' },
    { char: '🥤', category: 'food', keywords: 'cup with straw' },
    { char: '🧋', category: 'food', keywords: 'bubble tea' },
    { char: '🧃', category: 'food', keywords: 'beverage box' },
    { char: '🧉', category: 'food', keywords: 'mate' },
    { char: '🧊', category: 'food', keywords: 'ice cube' },

    // Activities
    { char: '⚽', category: 'activities', keywords: 'soccer ball' },
    { char: '🏀', category: 'activities', keywords: 'basketball' },
    { char: '🏈', category: 'activities', keywords: 'american football' },
    { char: '⚾', category: 'activities', keywords: 'baseball' },
    { char: '🥎', category: 'activities', keywords: 'softball' },
    { char: '🎾', category: 'activities', keywords: 'tennis' },
    { char: '🏐', category: 'activities', keywords: 'volleyball' },
    { char: '🏉', category: 'activities', keywords: 'rugby football' },
    { char: '🎱', category: 'activities', keywords: 'pool 8 ball' },
    { char: '🏓', category: 'activities', keywords: 'ping pong' },
    { char: '🏸', category: 'activities', keywords: 'badminton' },
    { char: '🥅', category: 'activities', keywords: 'goal net' },
    { char: '🏒', category: 'activities', keywords: 'ice hockey' },
    { char: '🏑', category: 'activities', keywords: 'field hockey' },
    { char: '🏏', category: 'activities', keywords: 'cricket' },
    { char: '⛳', category: 'activities', keywords: 'flag in hole' },
    { char: '🏹', category: 'activities', keywords: 'bow and arrow' },
    { char: '🎣', category: 'activities', keywords: 'fishing pole' },
    { char: '🥊', category: 'activities', keywords: 'boxing glove' },
    { char: '🥋', category: 'activities', keywords: 'martial arts uniform' },
    { char: '⛸️', category: 'activities', keywords: 'ice skate' },
    { char: '🎿', category: 'activities', keywords: 'skis' },
    { char: '🛷', category: 'activities', keywords: 'sled' },
    { char: '🥌', category: 'activities', keywords: 'curling stone' },
    { char: '🎯', category: 'activities', keywords: 'direct hit' },
    { char: '🎮', category: 'activities', keywords: 'video game' },
    { char: '🕹️', category: 'activities', keywords: 'joystick' },
    { char: '🎰', category: 'activities', keywords: 'slot machine' },
    { char: '🎲', category: 'activities', keywords: 'game die' },
    { char: '🧩', category: 'activities', keywords: 'puzzle piece' },
    { char: '🧸', category: 'activities', keywords: 'teddy bear' },
    { char: '♠️', category: 'activities', keywords: 'spade' },
    { char: '♥️', category: 'activities', keywords: 'heart' },
    { char: '♦️', category: 'activities', keywords: 'diamond' },
    { char: '♣️', category: 'activities', keywords: 'club' },
    { char: '♟️', category: 'activities', keywords: 'chess pawn' },
    { char: '🎭', category: 'activities', keywords: 'performing arts' },
    { char: '🎨', category: 'activities', keywords: 'artist palette' },
    { char: '🧵', category: 'activities', keywords: 'thread' },
    { char: '🧶', category: 'activities', keywords: 'yarn' },
    { char: '🎤', category: 'activities', keywords: 'microphone' },
    { char: '🎧', category: 'activities', keywords: 'headphone' },
    { char: '🎼', category: 'activities', keywords: 'musical score' },
    { char: '🎹', category: 'activities', keywords: 'musical keyboard' },
    { char: '🥁', category: 'activities', keywords: 'drum' },
    { char: '🎷', category: 'activities', keywords: 'saxophone' },
    { char: '🎺', category: 'activities', keywords: 'trumpet' },
    { char: '🎸', category: 'activities', keywords: 'guitar' },
    { char: '🎻', category: 'activities', keywords: 'violin' },
    { char: '🎬', category: 'activities', keywords: 'clapper board' },

    // Travel & Places
    { char: '🚗', category: 'travel', keywords: 'automobile car' },
    { char: '🚕', category: 'travel', keywords: 'taxi' },
    { char: '🚙', category: 'travel', keywords: 'suv' },
    { char: '🚌', category: 'travel', keywords: 'bus' },
    { char: '🚎', category: 'travel', keywords: 'trolleybus' },
    { char: '🏎️', category: 'travel', keywords: 'racing car' },
    { char: '🚓', category: 'travel', keywords: 'police car' },
    { char: '🚑', category: 'travel', keywords: 'ambulance' },
    { char: '🚒', category: 'travel', keywords: 'fire engine' },
    { char: '🚐', category: 'travel', keywords: 'minibus' },
    { char: '🚚', category: 'travel', keywords: 'delivery truck' },
    { char: '🚛', category: 'travel', keywords: 'articulated lorry' },
    { char: '🚜', category: 'travel', keywords: 'tractor' },
    { char: '🏍️', category: 'travel', keywords: 'motorcycle' },
    { char: '🚲', category: 'travel', keywords: 'bicycle' },
    { char: '🛴', category: 'travel', keywords: 'kick scooter' },
    { char: '🛹', category: 'travel', keywords: 'skateboard' },
    { char: '🛺', category: 'travel', keywords: 'auto rickshaw' },
    { char: '⛽', category: 'travel', keywords: 'fuel pump' },
    { char: '🚧', category: 'travel', keywords: 'construction' },
    { char: '🚥', category: 'travel', keywords: 'horizontal traffic light' },
    { char: '🚦', category: 'travel', keywords: 'vertical traffic light' },
    { char: '🛑', category: 'travel', keywords: 'stop sign' },
    { char: '⚓', category: 'travel', keywords: 'anchor' },
    { char: '⛵', category: 'travel', keywords: 'sailboat' },
    { char: '🛶', category: 'travel', keywords: 'canoe' },
    { char: '🚤', category: 'travel', keywords: 'speedboat' },
    { char: '🛳️', category: 'travel', keywords: 'passenger ship' },
    { char: '⛴️', category: 'travel', keywords: 'ferry' },
    { char: '🛥️', category: 'travel', keywords: 'motor boat' },
    { char: '🚢', category: 'travel', keywords: 'ship' },
    { char: '✈️', category: 'travel', keywords: 'airplane' },
    { char: '🛩️', category: 'travel', keywords: 'small airplane' },
    { char: '🛫', category: 'travel', keywords: 'airplane departure' },
    { char: '🛬', category: 'travel', keywords: 'airplane arrival' },
    { char: '🪂', category: 'travel', keywords: 'parachute' },
    { char: '🚁', category: 'travel', keywords: 'helicopter' },
    { char: '🚀', category: 'travel', keywords: 'rocket' },
    { char: '🛸', category: 'travel', keywords: 'ufo' },
    { char: '🛰️', category: 'travel', keywords: 'satellite' },
    { char: '🛎️', category: 'travel', keywords: 'bellhop bell' },
    { char: '🧳', category: 'travel', keywords: 'luggage' },
    { char: '⌛', category: 'travel', keywords: 'hourglass' },
    { char: '⏳', category: 'travel', keywords: 'hourglass flowing sand' },
    { char: '⌚', category: 'travel', keywords: 'watch' },
    { char: '⏰', category: 'travel', keywords: 'alarm clock' },
    { char: '⏱️', category: 'travel', keywords: 'stopwatch' },
    { char: '⏲️', category: 'travel', keywords: 'timer clock' },
    { char: '🕰️', category: 'travel', keywords: 'mantelpiece clock' },
    { char: '🌡️', category: 'travel', keywords: 'thermometer' },

    // Objects
    { char: '💡', category: 'objects', keywords: 'light bulb idea' },
    { char: '🔦', category: 'objects', keywords: 'flashlight' },
    { char: '🕯️', category: 'objects', keywords: 'candle' },
    { char: '🪔', category: 'objects', keywords: 'diya lamp' },
    { char: '🗑️', category: 'objects', keywords: 'wastebasket' },
    { char: '📦', category: 'objects', keywords: 'package' },
    { char: '📧', category: 'objects', keywords: 'e-mail' },
    { char: '📩', category: 'objects', keywords: 'envelope with arrow' },
    { char: '📨', category: 'objects', keywords: 'incoming envelope' },
    { char: '💌', category: 'objects', keywords: 'love letter' },
    { char: '📮', category: 'objects', keywords: 'postbox' },
    { char: '📯', category: 'objects', keywords: 'postal horn' },
    { char: '📜', category: 'objects', keywords: 'scroll' },
    { char: '📃', category: 'objects', keywords: 'page with curl' },
    { char: '📄', category: 'objects', keywords: 'facing up' },
    { char: '📑', category: 'objects', keywords: 'bookmark tabs' },
    { char: '📊', category: 'objects', keywords: 'bar chart' },
    { char: '📈', category: 'objects', keywords: 'chart increasing' },
    { char: '📉', category: 'objects', keywords: 'chart decreasing' },
    { char: '🗒️', category: 'objects', keywords: 'spiral notepad' },
    { char: '🗓️', category: 'objects', keywords: 'spiral calendar' },
    { char: '📆', category: 'objects', keywords: 'tear-off calendar' },
    { char: '📅', category: 'objects', keywords: 'calendar' },
    { char: '📋', category: 'objects', keywords: 'clipboard' },
    { char: '📁', category: 'objects', keywords: 'file folder' },
    { char: '📂', category: 'objects', keywords: 'open file folder' },
    { char: '🗂️', category: 'objects', keywords: 'card index dividers' },
    { char: '🗞️', category: 'objects', keywords: 'newspaper' },
    { char: '📰', category: 'objects', keywords: 'newspaper' },
    { char: '📓', category: 'objects', keywords: 'notebook' },
    { char: '📔', category: 'objects', keywords: 'notebook with decorative cover' },
    { char: '📒', category: 'objects', keywords: 'ledger' },
    { char: '📕', category: 'objects', keywords: 'closed book' },
    { char: '📗', category: 'objects', keywords: 'green book' },
    { char: '📘', category: 'objects', keywords: 'blue book' },
    { char: '📙', category: 'objects', keywords: 'orange book' },
    { char: '📚', category: 'objects', keywords: 'books' },
    { char: '📖', category: 'objects', keywords: 'open book' },
    { char: '🔖', category: 'objects', keywords: 'bookmark' },
    { char: '🔗', category: 'objects', keywords: 'link' },
    { char: '📎', category: 'objects', keywords: 'paperclip' },
    { char: '🖇️', category: 'objects', keywords: 'linked paperclips' },
    { char: '📏', category: 'objects', keywords: 'straight ruler' },
    { char: '📐', category: 'objects', keywords: 'triangular ruler' },
    { char: '📌', category: 'objects', keywords: 'pushpin' },
    { char: '📍', category: 'objects', keywords: 'round pushpin' },
    { char: '✂️', category: 'objects', keywords: 'scissors' },
    { char: '🖋️', category: 'objects', keywords: 'fountain pen' },

    // Symbols
    { char: '❤️', category: 'symbols', keywords: 'red heart' },
    { char: '🧡', category: 'symbols', keywords: 'orange heart' },
    { char: '💛', category: 'symbols', keywords: 'yellow heart' },
    { char: '💚', category: 'symbols', keywords: 'green heart' },
    { char: '💙', category: 'symbols', keywords: 'blue heart' },
    { char: '💜', category: 'symbols', keywords: 'purple heart' },
    { char: '🖤', category: 'symbols', keywords: 'black heart' },
    { char: '🤍', category: 'symbols', keywords: 'white heart' },
    { char: '🤎', category: 'symbols', keywords: 'brown heart' },
    { char: '💔', category: 'symbols', keywords: 'broken heart' },
    { char: '❣️', category: 'symbols', keywords: 'heart exclamation' },
    { char: '💕', category: 'symbols', keywords: 'two hearts' },
    { char: '💞', category: 'symbols', keywords: 'revolving hearts' },
    { char: '💓', category: 'symbols', keywords: 'beating heart' },
    { char: '💗', category: 'symbols', keywords: 'growing heart' },
    { char: '💖', category: 'symbols', keywords: 'sparkling heart' },
    { char: '💘', category: 'symbols', keywords: 'heart with arrow' },
    { char: '💝', category: 'symbols', keywords: 'heart with ribbon' },
    { char: '💟', category: 'symbols', keywords: 'heart decoration' },
    { char: '☮️', category: 'symbols', keywords: 'peace symbol' },
    { char: '✝️', category: 'symbols', keywords: 'latin cross' },
    { char: '☪️', category: 'symbols', keywords: 'star and crescent' },
    { char: '🕉️', category: 'symbols', keywords: 'om' },
    { char: '☸️', category: 'symbols', keywords: 'wheel of dharma' },
    { char: '✡️', category: 'symbols', keywords: 'star of david' },
    { char: '🔯', category: 'symbols', keywords: 'dotted six-pointed star' },
    { char: '🕎', category: 'symbols', keywords: 'menorah' },
    { char: '☯️', category: 'symbols', keywords: 'yin yang' },
    { char: '☦️', category: 'symbols', keywords: 'orthodox cross' },
    { char: '🛐', category: 'symbols', keywords: 'place of worship' },
    { char: '⛎', category: 'symbols', keywords: 'ophiuchus' },
    { char: '♈', category: 'symbols', keywords: 'aries' },
    { char: '♉', category: 'symbols', keywords: 'taurus' },
    { char: '♊', category: 'symbols', keywords: 'gemini' },
    { char: '♋', category: 'symbols', keywords: 'cancer' },
    { char: '♌', category: 'symbols', keywords: 'leo' },
    { char: '♍', category: 'symbols', keywords: 'virgo' },
    { char: '♎', category: 'symbols', keywords: 'libra' },
    { char: '♏', category: 'symbols', keywords: 'scorpio' },
    { char: '♐', category: 'symbols', keywords: 'sagittarius' },
    { char: '♑', category: 'symbols', keywords: 'capricorn' },
    { char: '♒', category: 'symbols', keywords: 'aquarius' },
    { char: '♓', category: 'symbols', keywords: 'pisces' },
    { char: '🆔', category: 'symbols', keywords: 'id button' },
    { char: '⚛️', category: 'symbols', keywords: 'atom symbol' },
    { char: '🉑', category: 'symbols', keywords: 'japanese acceptable button' },
    { char: '☢️', category: 'symbols', keywords: 'radioactive' },
    { char: '☣️', category: 'symbols', keywords: 'biohazard' },
    { char: '📴', category: 'symbols', keywords: 'mobile phone off' },
    { char: '📳', category: 'symbols', keywords: 'vibration mode' },

    // Flags
    { char: '🏁', category: 'flags', keywords: 'checkered flag' },
    { char: '🚩', category: 'flags', keywords: 'triangular flag' },
    { char: '🎌', category: 'flags', keywords: 'crossed flags' },
    { char: '🏴', category: 'flags', keywords: 'black flag' },
    { char: '🏳️', category: 'flags', keywords: 'white flag' },
    { char: '🏳️‍🌈', category: 'flags', keywords: 'rainbow flag' },
    { char: '🏳️‍⚧️', category: 'flags', keywords: 'transgender flag' },
    { char: '🏴‍☠️', category: 'flags', keywords: 'pirate flag' },
    { char: '🇦🇫', category: 'flags', keywords: 'afghanistan' },
    { char: '🇦🇽', category: 'flags', keywords: 'aland islands' },
    { char: '🇦🇱', category: 'flags', keywords: 'albania' },
    { char: '🇩🇿', category: 'flags', keywords: 'algeria' },
    { char: '🇦🇸', category: 'flags', keywords: 'american samoa' },
    { char: '🇦🇩', category: 'flags', keywords: 'andorra' },
    { char: '🇦🇴', category: 'flags', keywords: 'angola' },
    { char: '🇦🇮', category: 'flags', keywords: 'anguilla' },
    { char: '🇦🇶', category: 'flags', keywords: 'antarctica' },
    { char: '🇦🇬', category: 'flags', keywords: 'antigua & barbuda' },
    { char: '🇦🇷', category: 'flags', keywords: 'argentina' },
    { char: '🇦🇲', category: 'flags', keywords: 'armenia' },
    { char: '🇦🇼', category: 'flags', keywords: 'aruba' },
    { char: '🇦🇺', category: 'flags', keywords: 'australia' },
    { char: '🇦🇹', category: 'flags', keywords: 'austria' },
    { char: '🇦🇿', category: 'flags', keywords: 'azerbaijan' },
    { char: '🇧🇸', category: 'flags', keywords: 'bahamas' },
    { char: '🇧🇭', category: 'flags', keywords: 'bahrain' },
    { char: '🇧🇩', category: 'flags', keywords: 'bangladesh' },
    { char: '🇧🇧', category: 'flags', keywords: 'barbados' },
    { char: '🇧🇾', category: 'flags', keywords: 'belarus' },
    { char: '🇧🇪', category: 'flags', keywords: 'belgium' },
    { char: '🇧🇿', category: 'flags', keywords: 'belize' },
    { char: '🇧🇯', category: 'flags', keywords: 'benin' },
    { char: '🇧🇲', category: 'flags', keywords: 'bermuda' },
    { char: '🇧🇹', category: 'flags', keywords: 'bhutan' },
    { char: '🇧🇴', category: 'flags', keywords: 'bolivia' },
    { char: '🇧🇦', category: 'flags', keywords: 'bosnia & herzegovina' },
    { char: '🇧🇼', category: 'flags', keywords: 'botswana' },
    { char: '🇧🇷', category: 'flags', keywords: 'brazil' },
    { char: '🇮🇴', category: 'flags', keywords: 'british indian ocean territory' },
    { char: '🇻🇬', category: 'flags', keywords: 'british virgin islands' },
    { char: '🇧🇳', category: 'flags', keywords: 'brunei' },
    { char: '🇧🇬', category: 'flags', keywords: 'bulgaria' },
    { char: '🇧🇫', category: 'flags', keywords: 'burkina faso' },
    { char: '🇧🇮', category: 'flags', keywords: 'burundi' },
    { char: '🇰🇭', category: 'flags', keywords: 'cambodia' },
    { char: '🇨🇲', category: 'flags', keywords: 'cameroon' },
    { char: '🇨🇦', category: 'flags', keywords: 'canada' },
    { char: '🇮🇨', category: 'flags', keywords: 'canary islands' },
    { char: '🇨🇻', category: 'flags', keywords: 'cape verde' },
    { char: '🇧🇶', category: 'flags', keywords: 'caribbean netherlands' },
];
